### ISSUE TITLE
Provide correct default date format when locale is selected, e.g. German format is incorrect when no Format is specified

### ISSUE THREAD

**Issue by agruenberg** [melohagan/budibase-component-kasper-date-picker#1]
The german date format is usually dd.mm.yyyy. Even if I set local to de, the format is still yyyy-mm-dd H:i:s.

![Bildschirmfoto von 2022-10-19 12-22-19](https://user-images.githubusercontent.com/19472717/196665671-b1826ab3-f7b9-485e-8946-6351616ebbd6.png)
![Bildschirmfoto von 2022-10-19 12-22-01](https://user-images.githubusercontent.com/19472717/196665677-5fed5616-b7a2-4422-bb41-498cbf7c2291.png)

**Comment by melohagan** [comment]
Hey @agruenberg 

You can specify the format you want in the *Format* field

**Comment by agruenberg** [comment]
Ok, so the local is only for the language?

**Comment by melohagan** [comment]
The language and the order of the week days. 

I can rename this issue to provide a default locale format, for the case that no format has been provided in the *Format* field

**Comment by agruenberg** [comment]
Ok, I think this would be an enhancement, if the local format is also pre populated. Once again: GREAT!

**Comment by melohagan** [comment]
Default date formats added:

![Screenshot 2022-10-20 at 10 19 51](https://user-images.githubusercontent.com/101575380/196909373-62492217-a827-4aa3-9356-7c9da6fff2a7.png)

If you provide a custom format, this will override the default locale format:
![Screenshot 2022-10-20 at 10 20 37](https://user-images.githubusercontent.com/101575380/196909559-463e259e-e1f8-4863-84c9-36c1544ce06c.png)
