### ISSUE TITLE
Javascript does not produce the intended result

### ISSUE THREAD

**Issue by kzkondo** [melohagan/budibase-component-kasper-date-picker#11]
**Checklist**
- [✔️] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker single image
  - Budibase Version: 2.3.15
  - App Version: 1.5.0

**Describe the bug**
Javascript does not produce the intended result

**To Reproduce**
Write the following java script in the default value.
state.date is the value obtained using update state on another page.
The calendar picker gives the intended result, but the kasper-date-picker does not.

let date = $("State.date");
if(date){
	date = helpers.date($("State.date"),'YYYY/MM/DD')
}
else{
	date = helpers.date(new Date,'YYYY/MM/DD')
}
return date;

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.3
 - Browser chrome, safari
 - Version latest

**Comment by melohagan** [comment]
Hi @kzkondo 

This line of code: `date = helpers.date(new Date,'YYYY/MM/DD')` doesn't look correct, would it not be `new Date()`?

Closing for now. If you would like to re-open the issue, please provide some screenshots and the direct correct code being used.
