### ISSUE TITLE
Enhancement: No time part

### ISSUE THREAD

**Issue by agruenberg** [melohagan/budibase-component-kasper-date-picker#2]
As an enhancement I would like to suggest that the user should be able to choose if he/she want the date with or without time part.

**Comment by melohagan** [comment]
Hey @agruenberg 

You can specify that in the *Format* field 😃

**Comment by agruenberg** [comment]
Yes, sorry saw it to late. This component is really really GREAT! I like also the option to define min/max! Now I have to change nearly 100 default date components ;) Thank you so much!
