### ISSUE TITLE
Calendar should close after selecting a date

### ISSUE THREAD

**Issue by agruenberg** [melohagan/budibase-component-kasper-date-picker#5]
If a date ist selected via calendar, it should disappear after selection. Instead the calendar still is visible, as long as you click somewhere else on the form.

**Comment by melohagan** [comment]
![Screenshot 2022-10-20 at 10 35 40](https://user-images.githubusercontent.com/101575380/196913038-0b650434-cf2a-463e-b715-909e15a9b251.png)

Added a close on selection setting.
