### ISSUE TITLE
Cannot display dates after December 31, 2022

### ISSUE THREAD

**Issue by kzkondo** [melohagan/budibase-component-kasper-date-picker#7]
**Hosting**
 - Budibase Version: <version> 

 **Describe the bugs**
 - Cannot display dates after December 31, 2022
 - I've tried various settings, but nothing seems to change.

<img width="260" alt="スクリーンショット 2022-11-19 11 59 04" src="https://user-images.githubusercontent.com/93172658/202831188-24811e2b-b4d5-4a0f-802f-1b0a982a7fbc.png">

<img width="554" alt="スクリーンショット 2022-11-19 11 59 59" src="https://user-images.githubusercontent.com/93172658/202831250-44523cfe-8e9a-4e67-bfc3-96297c315d9a.png">

It seems that only January 2002 to December 2022 can be displayed.

**Comment by melohagan** [comment]
Hey @kzkondo 

Can you enter a date into the *Latest* field that is greater than Dec 2022 ?

**Comment by kzkondo** [comment]
> Hey @kzkondo
> 
> Can you enter a date into the _Latest_ field that is greater than Dec 2022 ?

Even if you enter it in the latest column, it will not be reflected.

<img width="830" alt="スクリーンショット 2022-11-22 8 44 19" src="https://user-images.githubusercontent.com/93172658/203180552-883437de-c3a5-4830-bc40-5d24604b730c.png">

<img width="998" alt="スクリーンショット 2022-11-22 8 44 52" src="https://user-images.githubusercontent.com/93172658/203180571-3b0adf69-fb0d-4732-8fd9-dc72dcdb32b0.png">

**Comment by melohagan** [comment]
Hey @kzkondo 

Thanks for raising this bug. It was originally caused by the format of the earliest/latest fields not matching the locale. 
I've updated the code in the latest version **1.4.1** that supports both the locale format `2030/12/01` or the standard `2030-12-01 00:00:00`
