### ISSUE TITLE
Add On Change Define actions 

### ISSUE THREAD

**Issue by kzkondo** [melohagan/budibase-component-kasper-date-picker#8]
Hi! @melohagan 

Thank you for creating a useful plugin.
Is it possible to add an action definition on change?
Since the calendar picker has that feature,
Kasper-date-picker is also very useful with that feature.

**Comment by melohagan** [comment]
This issue must be resolved first: https://github.com/Budibase/budibase/issues/8683

**Comment by melohagan** [comment]
On Change setting added!

**Comment by kzkondo** [comment]
Hi!@melohagan Thank you for your quick response! Even more convenient.
