### ISSUE TITLE
Plugin resets date to 01/01/2001 when  typing

### ISSUE THREAD

**Issue by doucwiki** [melohagan/budibase-component-kasper-date-picker#9]
I am trying to enter date by hand.  When hitting the last digit of the year the date resets automatically to 01/01/2001. 
BTW: When trying to pick year via arrow cannot go further back than 12 years. 

https://user-images.githubusercontent.com/123512091/215903400-03c76b28-3b28-42b8-94fb-21ea4228833c.MOV

**Comment by melohagan** [comment]
Hey @doucwiki 

I think that's just because `01/01/2001` is the default earliest date. Under the *Earliest* field, type in: `1900-01-01 00:00:00` and let me know if that helps!

**Comment by doucwiki** [comment]
Hi. Thought about that but deleting earliest date didn't have an effect. Entering the 1900 date solved the Problem. 

Thanks.
